apiVersion: v1
kind: Pod
metadata:
  labels:
    app: carpentries-workbench
  name: carpentries-incubator-reproducible-research
spec:
  containers:
  - name: workbench
    image: docker.io/carpentries/workbench-docker:latest
    workingDir: /home/rstudio/lessons
    command:
    - Rscript
    - --verbose
    - -e
    - sandpaper::serve(host = "0.0.0.0", port = "4321")
    ports:
    - containerPort: 4321
      hostPort: 4321
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /home/rstudio/lessons
      name: lesson-src
  volumes:
  - hostPath:
      path: ./
      type: Directory
    name: lesson-src
